function triangle(row) {
  const evaluate = (pair) =>{
    if (pair=='BG' || pair=='GB') letter = 'R'
    else if (pair=='RG' || pair=='GR') letter = 'B'
    else if (pair=='BR' || pair=='RB') letter = 'G'
    else letter = pair[0]
    return letter
  }
  if(row.length==1) return row
  let newRow=''
  for(i=0;i<row.length-1;i++){
    let pair = row[i]+row[i+1]
    newRow += evaluate(pair)
  }
  return triangle(newRow)
}

console.log(triangle("GBRBBGBGBRGBRBRGBGBBRGGGGBBRGRRBRGBRBBGBBRBRGRBRBRRBGGRRGRRBGGRGRBBRBGRGBBBRGBBRBBRRGGGRRRRGBGRRGRRRBBRGGRBRBBGBGBGRGRGGRBRGRGGBGBGRGBGGBGGRRRBRRGRBBBGRBBGRGRGBRBBBBGRBGRBBGRBBGRBGRGBBRRBGBRGBRRGRRRRGGRRRRRBRGBGGGGGBRGGBRRGGGRBBGRGRRGGGBRGGGRRBBGGBRRGRGRGRRGBRGRRBBGGRRRBGRRRRBBRBRGRBGRBRBBGGRGGRGRRGRGBGGRBRBBGRBBBGBGBBRRGRRRBGRRBGGBBBBBGBRBRBGBGBGGBBBGGBGRRBRRRBBBBBBRBRBBBBGRGRBGRBBGGGBRRBRRBGRBRRRBRRGBRGGBGRRGRRRBGBRBRRRRBRBRGGBBBBRBRGBGBRGRRGRBBGGRBBRBBGBGBBGGGGGBRRGRRBGRGBRRRBGRGBBGRBRRGBGGGBRGBBGRBGRGRGBGRGBBGBRBGRBRRGBGGRRGRBGRGBBGRBRGGBRBBRGGBGBBRGBGBBRGBGBRRGRGRRBBGBBRGBBRGBRBGBGBBBRBRBRBGRGBGGGBGBGBGGRBRGGBGGGGRBGGBBGRBRRGGBGRGRRRGGRBRBGBGGGGGRRGBBBBBRGRRRGBRBRBRGBGGGGRBBBBGRRRRRGBGBGGRRGGRBRRGBBGRRGGGGRBRGRRGGRRGBBBRGRRRGBBGBRBRBGBGBBGGBBRBGGGGRBBBBRRGRRBRGBGGGRRGRBBRBRRGBBRBGRR"))